### ISSUE TITLE
[BUG] Remote URLs and packages without versions raise an exception

### ISSUE THREAD

**Issue by mostafa** [CycloneDX/cyclonedx-python-lib#193]
I tried to run `cyclonedx-bom` on a requirements file ([a test fixture](https://github.com/CycloneDX/cyclonedx-python/blob/master/tests/fixtures/requirements-local-and-remote-packages.txt) and also a private repository of mine) and found that when the version is empty, the library raises an error. The error was introduced after I replaced the requirements parser in https://github.com/CycloneDX/cyclonedx-python/pull/327, and the affected line is:

https://github.com/CycloneDX/cyclonedx-python-lib/blob/9fce6bf853032de9b2eec1f2b20341c8fbe6f639/cyclonedx/output/json.py#L154

According to [the specification](https://cyclonedx.org/docs/1.4/xml/#type_component), the `version` field is not required/enforced.

```bash
$ cyclonedx-bom -r -i tests/fixtures/requirements-local-and-remote-packages.txt --format json
Traceback (most recent call last):
  File "/somewhere/.pyenv/versions/3.9.6/bin/cyclonedx-bom", line 8, in <module>
    sys.exit(main())
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx_py/client.py", line 260, in main
    CycloneDxCmd(args).execute()
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx_py/client.py", line 122, in execute
    output.output_to_file(filename=output_filename, allow_overwrite=self._arguments.output_file_overwrite)
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx/output/__init__.py", line 102, in output_to_file
    f_out.write(self.output_as_string().encode('utf-8'))
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx/output/json.py", line 117, in output_as_string
    self.generate()
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx/output/json.py", line 67, in generate
    bom_json = json.loads(self._specialise_output_for_schema_version(bom_json=bom_json))
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx/output/json.py", line 96, in _specialise_output_for_schema_version
    bom_json = self._recurse_specialise_component(bom_json=bom_json)
  File "/somewhere/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cyclonedx/output/json.py", line 147, in _recurse_specialise_component
    if self.component_version_optional() and bom_json[base_key][i]['version'] == "":
KeyError: 'version'
```

@madpah @jkowalleck WDYT?

**Comment by madpah** [comment]
Hey @mostafa - thanks for the report.

Version is now optional according to CycloneDX 1.4 - and looks like this has exposed a bug in the library.

Will get a fix raised :-)

**Comment by madpah** [comment]
@mostafa - will leave this open for a bit to allow you to validate the fix that has been released.

**Comment by mostafa** [comment]
@madpah Works like a charm! 👌

**Comment by madpah** [comment]
Awesome - thanks for confirming @mostafa.
