### ISSUE TITLE
Components not properly in dep tree nor BOM

### ISSUE THREAD

**Issue by jkugler** [CycloneDX/cyclonedx-python-lib#540]
This is version 6.4.0

Components with unique bom_refs, but the same name, will generate an error when trying to render a dependency tree. Given this script:
```python
#!/usr/bin/env python3

from cyclonedx.model.bom import Bom
from cyclonedx.model.component import Component, ComponentType
from cyclonedx.output.json import JsonV1Dot5

bom = Bom()
bom.metadata.component = root_component = Component(
    name='myApp',
    type=ComponentType.APPLICATION,
    bom_ref="myApp"
)

component1 = Component(
    type=ComponentType.LIBRARY,
    name='some-component',
    bom_ref="some-component"
)
bom.components.add(component1)
bom.register_dependency(root_component, [component1])

component2 = Component(
    type=ComponentType.LIBRARY,
    name='some-library',
    bom_ref="some-library1"
)
bom.components.add(component2)
bom.register_dependency(component1, [component2])

component3 = Component(
    type=ComponentType.LIBRARY,
    name='some-library',
    bom_ref="some-library2"
)
bom.components.add(component3)
bom.register_dependency(component1, [component3])

print(JsonV1Dot5(bom).output_as_string(indent=2))
```
I get this error when I run it:
```
Traceback (most recent call last):
  File "/Users/tek30584/programming/cdx_lib_bugs/./duplicate_name_bug.py", line 38, in <module>
    print(JsonV1Dot5(bom).output_as_string(indent=2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tek30584/programming/cdx_lib_bugs/.venv/lib/python3.11/site-packages/cyclonedx/output/json.py", line 82, in output_as_string
    self.generate()
  File "/Users/tek30584/programming/cdx_lib_bugs/.venv/lib/python3.11/site-packages/cyclonedx/output/json.py", line 70, in generate
    bom.validate()
  File "/Users/tek30584/programming/cdx_lib_bugs/.venv/lib/python3.11/site-packages/cyclonedx/model/bom.py", line 600, in validate
    raise UnknownComponentDependencyException(
cyclonedx.exception.model.UnknownComponentDependencyException: One or more Components have Dependency references to Components/Services that are not known in this BOM. They are: {<BomRef 'some-library2'>}
```

**Comment by jkowalleck** [comment]
will add test cases to older versions, for regression and showcasing-purposes,
and then forward-port those and add fixes.

I am planning to have all affected major versions fixed.

**Comment by jkugler** [comment]
> the issue does not rely on same name of components, but the fact that both component have an equal (not identical) bom_ref - with a None value.

I'm not understanding this. All the components in the example script have unique `bom_ref` values.

**Comment by jkowalleck** [comment]
did some research and found, that `component3` was not added to the BOM.
This is an expected behavior, as the properties relevant for equality of `component2` are the same as of `component3`.


Per Specification, the minimal set of equality-properties of Components are: type, group, name [, version]
Bom-ref is not an identity-property nor an equality property. Bom-ref's purpose is linking elements, it does not have any meaning besides this purpose.

As all is ass expected, I'll close this issue.
This Issue is not locked, so further discussion may take place here, instead of opening another issue.

**Comment by jkugler** [comment]
Ah, that is interesting. I would expect a "guaranteed unique" property would be used for testing "unique-ness." But I understand. I guess I'm drawing too much on my database experience. :) Thanks for digging in to this and doing the research!

**Comment by jkowalleck** [comment]
@madpah FYI

**Comment by jkowalleck** [comment]
this issue should have been losed via https://github.com/CycloneDX/cyclonedx-python-lib/pull/587

**Comment by eugenhoffmann** [comment]
From my perspective, it seems that this issue does not specifically address the same problem.

To reproduce the second case mentioned [here](https://github.com/CycloneDX/cyclonedx-python-lib/issues/540#issuecomment-2049587905), you can use the provided example BOM file [UnkCompDepEx.json](https://github.com/CycloneDX/cyclonedx-python-lib/files/15137280/UnkCompDepEx.json).

Here is a code example that reads the BOM file and writes it to a string:

```
import json
from cyclonedx.model.bom import Bom
from cyclonedx.output.json import JsonV1Dot5

with open("UnkCompDepEx.json") as input_json:
    deserialized_bom = Bom.from_json(data=json.loads(input_json.read()))

print(JsonV1Dot5(deserialized_bom).output_as_string(indent=2))
```

When running this code, I get the 'UnknownComponentDependencyException' error message:

```
File "F:\Git\rsb-sbom\venv\lib\site-packages\cyclonedx\output\json.py", line 83, in output_as_string
  self.generate()
File "F:\Git\rsb-sbom\venv\lib\site-packages\cyclonedx\output\json.py", line 71, in generate
  bom.validate()
File "F:\Git\rsb-sbom\venv\lib\site-packages\cyclonedx\model\bom.py", line 658, in validate
  raise UnknownComponentDependencyException(
cyclonedx.exception.model.UnknownComponentDependencyException: One or more Components have Dependency references to Components/Services that are not known in this BOM. They are: {<BomRef 'y2' id=2229836430400>, <BomRef 'x2' id=2229836429824>}
```
Feel free to reach out if you need further assistance

**Comment by wkoot** [comment]
I think the problem lies in the deduplication of SortedSet; elements are not added to the set when their value matches.
The equality operator in the Component class compares the objects' hash values, which can be the same although content differs.

Example:
```
>>> from cyclonedx.model.component import Component, BomRef
>>> c1 = Component(bom_ref=BomRef(value='71dd3e04-ac87-4f23-818f-3cd9a17bc785'), name='pip')
>>> c2 = Component(bom_ref=BomRef(value='3d383d8b-af76-462f-9701-503cb6c5eb00'), name='pip')
>>> c1 == c2
True
```

**Comment by jkowalleck** [comment]
> I think the problem lies in the deduplication of SortedSet; elements are not added to the set when their value matches. The equality operator in the Component class compares the objects' hash values, which ignores the nested `BomRef` object.
> 
> Example:
> 
> ```
> >>> from cyclonedx.model.component import Component, BomRef
> >>> c1 = Component(bom_ref=BomRef(value='71dd3e04-ac87-4f23-818f-3cd9a17bc785'), name='pip')
> >>> c2 = Component(bom_ref=BomRef(value='3d383d8b-af76-462f-9701-503cb6c5eb00'), name='pip')
> >>> c1 == c2
> True
> ```
> 
> If object equality is not defined by their `BomRef`, the assumption that `BomRef` is a foreign key does not hold. The related PR #587 seems to deal with a similar issue, where certain fields were omitted from the lt operator.



`bom-ref` is intentional not part of the `__eq__` comparison - it has no meaning, it is a mere reference-indicator.
`c1` and `c2` are the same component -> both are `pip`

**Comment by wkoot** [comment]
Fair point but when there are multiple BOM files sourced in the python script, this is no longer applicable.
When merging sets of `Vulnerabilitie` objects from separate BOM files, they refer to their own `Component`.
If only one of these is added to the global list of `Components`, all references will fail since they assume they can use `BomRef`

**Comment by wkoot** [comment]
> `bom-ref` is intentional not part of the `__eq__` or `__hash__` method - it has no meaning, it is a mere reference-indicator. `c1` and `c2` are the same component -> both are `pip`

I have submitted https://github.com/CycloneDX/cyclonedx-cli/issues/399 to address the discrepancy between the implementation in python and c# libraries.
It is however unclear to me as to where the intended behaviour is specified. Do you know if it is somewhere in the spec?
There's nothing mentioned in the [CycloneDX JSON Reference](https://cyclonedx.org/docs/1.5/json/#metadata_component_bom-ref), although that's arguably the wrong location to explain deduplication.

Note also that the [MergeTests for the C# library](https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/main/tests/CycloneDX.Utils.Tests/MergeTests.cs#L109) explicitly do not take `bom-ref` of components into account.
For that matter, this also isn't tested in neither [test_component.py](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/tests/test_component.py) nor [test_model_component.py](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/tests/test_model_component.py).

**Comment by wkoot** [comment]
> `bom-ref` is intentional not part of the `__eq__` or `__hash__` method - it has no meaning, it is a mere reference-indicator. `c1` and `c2` are the same component -> both are `pip`

I was wondering if duplicate components in _nested_ objects are supposed to be deduplicated, or if they should not be.
Currently, the equality check is only called in set addition - so not in any parent component within the tree.
See also https://github.com/aquasecurity/trivy/discussions/7532#discussioncomment-10677327; should nesting these components be a solution?

**Comment by jkowalleck** [comment]
> > `bom-ref` is intentional not part of the `__eq__` or `__hash__` method - it has no meaning, it is a mere reference-indicator. `c1` and `c2` are the same component -> both are `pip`
> 
> I was wondering if duplicate components in _nested_ objects are supposed to be deduplicated, or if they should not be. Currently, the equality check is only called in set addition - so not in any parent component within the tree. See also [aquasecurity/trivy#7532 (comment)](https://github.com/aquasecurity/trivy/discussions/7532#discussioncomment-10677327); should nesting these components be a solution? However, if nesting would be an allowed solution - wouldn't that also mean vulnerabilities _have to_ be duplicated?

not intended for nested of parallels, as they may contextualize the individual outer component.

**Comment by wkoot** [comment]
It seems that deserialization silently loads broken bom data, in the [case of duplicate components as earlier referred to](https://github.com/aquasecurity/trivy/discussions/7532).
For easier reproduction, I see that even the sample testdata output as reported in https://github.com/CycloneDX/cyclonedx-cli/issues/399 suffices:
```python
>>> with open('test/out.json', mode="r") as testfile:
...   json_bom = load(testfile)
>>> len(json_bom['components'])
4
>>> len(json_bom['dependencies']) 
2
>>> bom = Bom.from_json(json_bom)
>>> len(bom.components)
2
>>> len(bom.dependencies) 
2
>>> bom.validate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib\site-packages\cyclonedx\model\bom.py", line 666, in validate
    raise UnknownComponentDependencyException(
cyclonedx.exception.model.UnknownComponentDependencyException: One or more Components have Dependency references to Components/Services that are not known in this BOM. They are: {<BomRef 'test22' id=2111773432208>, <BomRef 'test21' id=2111773432160>}
```

Because `Bom.from_json()` doesn't throw an error, there's no telling what data is actually lost during deserialization.
I'm not sure if this still belongs in the current issue, or if I should open a separate ticket with these findings.

**Comment by jkowalleck** [comment]
> I'm not sure if this still belongs in the current issue, or if I should open a separate ticket with these findings.

please open a dedicated issue for that.

**Comment by jkowalleck** [comment]
A preview of the fix/feature is available via https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v9.0.1-rc.1

**Comment by jkowalleck** [comment]
> Although the initial report is fixed (verified in `cyclonedx-python-lib==9.1.0`), testing this highlights another issue. When the `bom_ref`s are _not_ unique, some weird clash is happening that (silently) provides incorrect output.

please open a new ticket for this, and provide a reproducible example.
