### ISSUE TITLE
[BUG] validate JSON for 1.3

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#612]
validation of 

```json
{
  "$schema": "http://cyclonedx.org/schema/bom-1.3.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
...
}
```

fails with unexpected

```text
Failure
Traceback (most recent call last):
  File ".../cyclonedx-python-lib/.venv/lib/python3.11/site-packages/ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../cyclonedx-python-lib/tests/test_validation_json.py", line 112, in test_validate_no_none
    self.assertIsNone(validation_error)
AssertionError: <ValidationError: "'http://cyclonedx.org/schema/bom-1.3.schema.json' is not one of ['http://cyclonedx.org/schema/bom-1.3a.schema.json']"> is not None

```

**Comment by jkowalleck** [comment]
caused by 
*  https://github.com/CycloneDX/specification/issues/402
*  https://github.com/CycloneDX/specification/pull/403
